---

sudo: required

env:
  global:
    - ANSIBLE_VERSION: 2.5
    - secure: ZlxasD2VoNvPlrh+evLve9s5KiR4/Ocs+GuGbuT+kOa360EwlktaFWIs0QjJ8AbNk8Yau7vNUbraEYsM9/GSkNWeD1vzasG9VxbWYZr5pOUW1uOW7CCqbcrPZTJ2OExBGwtJ+feWHHtQRFPgTW7sqt+qGd+LniLo3E3DNIWU92OztXywVOyPJgWl/DjX6zutx2lmABl6vsQ+Ujh9AcTkuaMTJxb1Cbfcinv3FHiMqD+Gpf6ZIhtsLqEzhUslpYNKkj21waTWf3IUajYrWMkNb2Fdh86RwOBfbeTe4e7nx6w0RZQMyuFoRrzDAmk2ETWStGeobTvanez5R0iKRtA3nmU//skQkpqe726s/NoQctoy4DDPoBkxgwvluf+5HF2fbEo0qSxSKxz56c2L8sGssbkihUdRiXth18JwU8jxeEhinrdV0pDmHePFJKUNEbCVHT8Xf+460tNtigULnkHKal9gKNtRFKT+mZIEXVoJ2BWRLrUBIqjWNHCgiknZQb+FlzR38G4cWK6z1RlX4BCcO12zjWTA8J9kA1DVGYkY/Y1xkAp+6NLb7KK1OthvsnT8XI+OzYkU9fdcQjbfx6JC/ltUs4ffkl6ubwwJfnw3q59f2JrWXTNbo46/4Pe4JFwM/lJgi3BtNYKFbATfEkp2pcMGD0iWCJym0Pww50SR8h0=
    - secure: CynLDirRqPxgtQicHjERIka6MQ+Q7ytZyr1pKMy+S1CCYN7euwpP6y6XytqrSEOexEevY+a8d15yGXZC27u9wID7i4l8dyCsQWY3i61wFOuaIM6EfhRI4tJ8q9I4g06NJL5evVXm+plBvJ+SmXTq/Pc6/lBgeBmZ+IQ4afv1iYo1fBoK1dxJjl+TbRSRG0HW+QIfzhvr5xus4e4uP3cmRWegigBuBCdxi6fjcLYvCXV8+5oS1avhTzJJXP86pZcbPNHfbJG2rhaPx3iH51vk7b6ffXhzFN+lTuMaSBe66JIqRRmeBSmZ2Itbbb3UWD+5TL63YjLDNWLHIOpZ/NBwdbfAYbIXoO1FPtLy00TRlPguFHHLiEjKtwXEMfOCTbYmJvrACwbEyPDkfGh/Zuq7I2S/XObBp89OscZJc15gG/9jWH8/9BJdu/yclgR3YJHF7OD+l5fZIog2pG2Cg+4ixI95QI7TQvhwA1n6hK7AnGLEesyEg3gERo0a0L2OIgXGBDgYo/viy0vDGqyhH7FNODH5vom64w9vsARaS4ExXkwZGPt1FXnt+uK2st6U/gpKnq+EtY2gXeZsX2JIUAjyvWV8upbtKoUuoFlnzjk+G/DA6sbMKuni3X6m7n6b+UgHr9rCV+DAmWv+hCix/cNfxIbjYJWP00A6tobq0msgetg=
  matrix:
    - DISTRIBUTION: centos
      VERSION: 7
    - DISTRIBUTION: ubuntu
      VERSION: 16.04

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install --only-upgrade git
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch origin docker-tests
  - git worktree add docker-tests origin/docker-tests
  - curl https://github.com/open-io/ansible-role-openio-gridinit/blob/master/library/gridinitcmd.py --create-dirs -o library/gridinitcmd.py
  - sudo pip install --upgrade pip
  - sudo pip install ansible-lint yamllint

script:
  - ansible-lint . -x ANSIBLE0016 -x ANSIBLE0012
  - yamllint .
  - ./docker-tests/docker-tests.sh
  - SUT_ID=$(docker ps -qa) ./docker-tests/functional-tests.sh

...
