---
- hosts: all
  become: true
  vars:
    NS: TRAVIS
  roles:
    - role: repository
      openio_repository_mirror_host: 'mirror2.openio.io'
      openio_repository_products:
        sds:
          release: "17.04"
        oiofs-travis:
          release: "17.04"
          user: travisoiofs_id
          password: NehnXW4ErUEMYu8Sndju65n
    - role: gridinit
      openio_gridinit_namespace: "{{ NS }}"
      openio_gridinit_conf_location: "{{ openio_gridinit_conf_confd }}/*"
    - role: role_under_test
      oiofs_mountpoints:
        - path: /mnt/oiofs-1/mnt
          state: present
          account: travis_project
          cache_directory: /mnt/oiofs-1/cache
          container: travis_container
          # force_mkfs: true
          log_level: INFO
          oioproxy_host: "{{ lookup('env','IPVAGRANT') }}"
          redis_server: "{{ lookup('env','IPVAGRANT') }}:6011"
          # for CI only
          cache_timeout: 0
          ignore_flush: false
...
