---

- name: "oiofs: Unmount filesystem (by stopping gridinit service)"
  gridinitcmd:
    name: "{{ mountpoint.namespace | default(oiofs_mountpoint_default_namespace) }}-oiofs-{{ mountpoint_id }}"
    state: stop
  ignore_errors: true

- name: 'oiofs: Remove mountpoint as a gridinit service'
  include_role:
    name: gridinit
  vars:
    - openio_gridinit_services:
      - name: "oiofs-{{ mountpoint_id }}"
        namespace: "{{ mountpoint.namespace | default(oiofs_mountpoint_default_namespace) }}"
        state: absent

- name: 'oiofs: Remove oiofs configuration file'
  file:
    path: "{{ openio_oiofs_conf_directory }}/{{ mountpoint_id }}.json"
    state: absent

...
