---

- name: "oiofs: Unmount filesystem (by stopping gridinit service)"
  command: "gridinit_cmd stop oiofs-{{ mountpoint_id }}"

- name: 'oiofs: Remove mountpoint as a gridinit service'
  include_role:
    name: ansible-role-openio-gridinit
  vars:
    - openio_gridinit_services:
      - name: "oiofs-{{ mountpoint_id }}"
        namespace: "{{ mountpoint.namespace | default(oiofs_mountpoint_default_namespace) }}"
        state: absent

- name: 'oiofs: Remove oiofs configuration file'
  file:
    path: "{{ openio_oiofs_conf_directory }}/{{ mountpoint_id }}.json"
    state: absent

...
