---

- name: "oiofs: Unmount filesystem"
  shell: "grep -q ' on {{ mountpoint.path }} type fuse.oiofs-fuse ' /proc/mounts && fusermount -u {{ mountpoint.path }} || true"

- name: 'oiofs: Remove mountpoint as a gridinit service'
  include_role:
    name: ansible-role-openio-gridinit
  tags:
    - configure
  vars:
    - openio_gridinit_services:
      - name: "oiofs-{{ mountpoint_id }}"
        namespace: "{{ mountpoint.namespace | default(oiofs_mountpoint_default_namespace) }}"
        state: absent

- name: 'oiofs: Remove oiofs configuration file'
  file:
    path: "{{ openio_oiofs_conf_directory }}/{{ mountpoint_id }}.json"
    state: absent

...
