---
- name: 'oiofs: Setup SDS namespace configuration if not already present'
  template:
    src: "sds_ns.cfg.j2"
    dest: "{{ openio_sds_conf_directory }}/{{ mountpoint.namespace | default(oiofs_mountpoint_default_namespace) }}"
    force: false
    owner: '{{ openio_oiofs_cfg_user }}'
    group: '{{ openio_oiofs_cfg_group }}'
    mode: 0644

- name: 'Check given mountpoint redis config: not more than one'
  fail:
    msg: 'You can only specify one of: `redis_server` or `redis_sentinel_servers` per mountpoint'
  when:
    - mountpoint.redis_server is defined
    - mountpoint.redis_sentinel_servers is defined

- name: 'Check given mountpoint redis config: cluster cannot be empty'
  fail:
    msg: 'If you specify a `redis_sentinel_servers`, it cannot be empty'
  when:
    - mountpoint.redis_server is not defined
    - mountpoint.redis_sentinel_servers is defined
    - (mountpoint.redis_sentinel_servers | length) < 1

- name: 'oiofs: Setup oiofs configuration'
  template:
    src: "oiofs.cfg.j2"
    dest: "{{ openio_oiofs_conf_directory }}/{{ mountpoint_id }}.json"
    owner: '{{ openio_oiofs_cfg_user }}'
    group: '{{ openio_oiofs_cfg_group }}'
    mode: 0644
  register: _oiofs_conf

- name: Check if OIOFS is already present in container
  command: "openio reference show {{ mountpoint.container | default(oiofs_mountpoint_default_container) }} \
     --oio-account {{ mountpoint.account | default(oiofs_mountpoint_default_account) }} \
     --oio-ns {{ mountpoint.namespace | default(oiofs_mountpoint_default_namespace) }} \
     -c meta.oiofs_chunk_size"
  register: oiofs_mkfsed
  changed_when: false
  failed_when: false

- name: "oiofs: Create the filesystem inside container"
  shell: "mkfs.oiofs -C {{ openio_oiofs_conf_directory }}/{{ mountpoint_id }}.json \
    -v {% if mountpoint.force_mkfs | default(oiofs_mountpoint_default_force_mkfs) %} -f {% endif %} \
    -u {{ mountpoint.user | default(oiofs_mountpoint_default_user) }} \
    -g {{ mountpoint.group | default(oiofs_mountpoint_default_group) }} \
    -m {{ mountpoint.mode | default(oiofs_mountpoint_default_mode) }} \
    -c {{ mountpoint.chunk_size | default(oiofs_mountpoint_default_chunk_size) }} \
    -i  {{ mountpoint.inode_by_container | default(oiofs_mountpoint_default_inode_by_container) }} \
    {{ mountpoint.namespace | default(oiofs_mountpoint_default_namespace) }}/\
    {{ mountpoint.account | default(oiofs_mountpoint_default_account) }}/\
    {{ mountpoint.container | default(oiofs_mountpoint_default_container) }}"
  when: oiofs_mkfsed.rc != 0 or (mountpoint.force_mkfs | default(oiofs_mountpoint_default_force_mkfs))

- name: 'oiofs: Ensure OpenIO oiofs mountpoint directory exists'
  file:
    path: "{{ mountpoint.path }}"
    owner: root
    group: root
    state: directory
    mode: 0750

- name: 'oiofs: Ensure oiofs cache directory exists'
  file:
    path: "{{ mountpoint.cache_directory }}"
    owner: root
    group: root
    state: directory
    mode: 0750

- name: 'oiofs: Ensure oiofs cache recovery directory exists'
  file:
    path: "{{ mountpoint.recovery_cache_directory }}"
    owner: root
    group: root
    state: directory
    mode: 0750
  when: mountpoint.recovery_cache_directory is defined

- name: 'oiofs: Setup mountpoint as a gridinit service'
  template:
    src: "gridinit_oiofs.conf.j2"
    dest: "{{ openio_gridinit_conf_confd + '/' + (mountpoint.namespace |
      default(oiofs_mountpoint_default_namespace)) + '/oiofs-' + mountpoint_id + '.conf'
      if openio_gridinit_per_ns else openio_gridinit_conf_confd + '/' + (mountpoint.namespace |
      default(oiofs_mountpoint_default_namespace)) + '-oiofs-' + mountpoint_id + '.conf' }}"
    owner: openio
    group: openio
    mode: 0644
  register: _gridinit_conf

- name: 'oiofs: reload gridinit config files'
  command: 'gridinit_cmd reload'
  when: _oiofs_conf.changed or _gridinit_conf.changed

- name: 'oiofs: mount filesystem'
  command: 'gridinit_cmd start \
    {{ mountpoint.namespace | default(oiofs_mountpoint_default_namespace) }}-oiofs-{{ mountpoint_id }}'
  when: _oiofs_conf.changed or _gridinit_conf.changed
...
